#!/bin/bash
#ProcServer
#

start()
{
	/bin/bash /usr/local/bin/procServerStart.sh
}

stop()
{
	/bin/bash /usr/local/bin/procServerStop.sh
}

status()
{
	pid=`pidof procServer`
	if [ "$pid" ];then
		echo "ProcServer running with pid: $pid"
	else
		echo "ProcServer stopped"
	fi
}
case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		stop
		sleep 1
		start
	;;
	status)
		status
	;;
esac
exit 0
